import os

from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QLabel, QTableWidget, QTableWidgetItem, QHeaderView,
)
from PySide6.QtCore import Qt


FILE_TYPE_LABELS = {
    "obs": "Observation Data",
    "nav": "GPS Navigation",
    "gnav": "GLONASS Navigation",
    "hnav": "GEO Navigation",
    "qnav": "QZSS Navigation",
    "lnav": "Galileo Navigation",
    "cnav": "BeiDou Navigation",
    "inav": "IRNSS Navigation",
    "sbs": "SBAS Messages",
}


class ConversionStatus(QWidget):
    """Displays a table of files generated by convbin."""

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)

        self._title = QLabel()
        self._title.setStyleSheet("font-weight: bold; font-size: 13px;")
        layout.addWidget(self._title)

        self._table = QTableWidget()
        self._table.setColumnCount(4)
        self._table.setHorizontalHeaderLabels(["Status", "Type", "File", "Size"])
        self._table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
        self._table.verticalHeader().setVisible(False)
        self._table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self._table.setSelectionMode(QTableWidget.SelectionMode.NoSelection)
        layout.addWidget(self._table)

        self._error_label = QLabel()
        self._error_label.setStyleSheet("color: red;")
        self._error_label.setWordWrap(True)
        self._error_label.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        self._error_label.setVisible(False)
        layout.addWidget(self._error_label)

    def set_results(self, label: str, result: dict):
        """Populate the table from a converter result dict."""
        self._title.setText(label)
        self._error_label.setVisible(False)

        if result.get("returncode", 0) != 0:
            stderr = result.get("stderr", "")
            if stderr:
                self._error_label.setText(f"convbin warning/error:\n{stderr}")
                self._error_label.setVisible(True)

        file_keys = [k for k in result if k not in ("returncode", "stdout", "stderr")]
        all_types = list(FILE_TYPE_LABELS.keys())

        self._table.setRowCount(len(all_types))
        for row, ftype in enumerate(all_types):
            if ftype in file_keys:
                status_item = QTableWidgetItem("✓")
                status_item.setForeground(Qt.GlobalColor.darkGreen)
                path = result[ftype]
                size = os.path.getsize(path)
                size_str = _format_size(size)
                file_item = QTableWidgetItem(os.path.basename(path))
            else:
                status_item = QTableWidgetItem("—")
                status_item.setForeground(Qt.GlobalColor.gray)
                file_item = QTableWidgetItem("Not generated")
                file_item.setForeground(Qt.GlobalColor.gray)
                size_str = "—"

            status_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self._table.setItem(row, 0, status_item)

            type_item = QTableWidgetItem(FILE_TYPE_LABELS[ftype])
            self._table.setItem(row, 1, type_item)
            self._table.setItem(row, 2, file_item)

            size_item = QTableWidgetItem(size_str)
            size_item.setTextAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
            self._table.setItem(row, 3, size_item)

    def clear(self):
        self._table.setRowCount(0)
        self._title.setText("")
        self._error_label.setVisible(False)


def _format_size(size: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024:
            return f"{size:.1f} {unit}" if unit != "B" else f"{size} {unit}"
        size /= 1024
    return f"{size:.1f} TB"
